### ISSUE TITLE
Ignore files with cloc

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/sardina#9]
Find an option for `cloc` to ignore the files contained in `ignored_files.py`. Also add `bootstrap-dark.css` to the ignored files.

**Comment by e-caste** [comment]
Reopening since, when not using `dev_mode` and `keep_repos`, `_find_ignored_files()` returns an empty list. Otherwise, it works fine.

**Comment by alecello** [comment]
@e-caste Indeed, I generate the list before actually cloning the repository, stupid mistake 😅
